sudo: required
dist: xenial
language: node_js
node_js:
  - '7.2'

addons:
apt:
  sources:
    - google-chrome
    - firefox
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - ng github-pages:deploy
